#!/usr/bin/bash

_cvpn() {
    local prev
    _get_comp_words_by_ref -n : prev

    if [ ${prev} = "cvpn" ]; then
        __cvpn_subcmds
    fi 

    if [ ${prev} = "download" ] || [ ${prev} = "ls" ] || [ ${prev} = "list" ]; then
        __cvpn_list
    fi 
}

__cvpn_subcmds() {
    local cur
    _get_comp_words_by_ref -n : cur

    local subcmds="ls download upload find completions"
    COMPREPLY=( $(compgen -W "${subcmds}" -- "${cur}") );
}

__cvpn_list() {    
    local cur prev
    _get_comp_words_by_ref -n : cur prev

    local IFS=$'\n'
    local separator='/'
    local count_of_slash=$(awk -F"${separator}" '{print NF-1}' <<< "${cur}")
 
    local opts=$(
        while read line
        do
            echo "'${line}'"
        done < %s
    );

    local new_opts=$(
        while read line
        do
            local tmp=$(awk -F"${separator}" '{print NF-1}' <<< "${line}")
            if [ ${tmp} -eq ${count_of_slash} ] || [ ${tmp} -eq $((${count_of_slash}+1)) ]; then
                echo "${line}"
            fi
        done <<< "${opts}"
    );

    if [ "${#new_opts}" != "0" ]; then
        opts="${new_opts}"
    fi

    COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") ); IFS=${defaultIFS}
}

complete -F _cvpn cvpn